
include: package:lints/recommended.yaml


analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
  exclude:
    - "lib/src/api/generated_code/**"
