  targets:
    $default:
      builders:
        swagger_dart_code_generator:
          options:
            input_urls:
              - "https://raw.githubusercontent.com/Sensibo/sensibo.github.io/master/sensibo.openapi.yaml"
