name: sensibo
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/CyBear-Jinni/sensibo

environment:
  sdk: ^3.2.3


dependencies:
  chopper: ^7.0.10
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  build_runner: ^2.4.7
  chopper_generator: ^7.0.7
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^2.10.4