name: sensibo
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/CyBear-Jinni/sensibo

environment:
  sdk: ^3.2.3


dependencies:
  chopper: ^6.1.1
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.10.4