name: sensibo
description: Control Sensibo devices. You can find a Sensibo Sky device for AC control and Sensibo Elements device.
version: 1.0.2
repository: https://github.com/CyBear-Jinni/sensibo
homepage: https://sensibo.com

environment:
  sdk: ^3.2.3


dependencies:
  chopper: ^7.0.10
  collection: ^1.18.0
  http: ^1.1.2
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  build_runner: ^2.4.7
  chopper_generator: ^7.0.7
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^2.10.4